import json
import os
import pathlib
import tempfile
import unittest
from pathlib import Path
from unittest import mock

import pytest
from hypothesis import given
from hypothesis import strategies as st

from mmif import (
    AnnotationTypes, 
    Document, 
    Mmif
)
from mmif.utils import sequence_helper as sqh
from mmif.utils import text_document_helper as tdh
from mmif.utils import timeunit_helper as tuh
from mmif.utils import video_document_helper as vdh
from mmif.utils import workflow_helper as wfh
from tests import mmif_examples 


class TestTimeunitHelper(unittest.TestCase):
    FPS = 100  # 1 frame == 10 ms

    @given(st.integers(min_value=300, max_value=10000))
    def test_convert(self, value):
        # using hypothesis library, test time unit conversions 
        # four-way between second, millisecond, framenum, and isoformat 
        for tu1 in ['s', 'm', 'f', 'i']:
            for tu2 in ['s', 'm', 'f', 'i']:
                if tu1 == tu2:
                    continue
                # since the input (generated by hypothesis) is always integer/millisecond
                # I'm going to dual round-trip conversion
                # ms > tu1 > tu2 > tu1 > ms 
                # then see the ends are equal (enough)
                in_t = tuh.convert(value, 'm', tu1, self.FPS)
                converted = tuh.convert(in_t, tu1, tu2, self.FPS)
                converted_back = tuh.convert(converted, tu2, tu1, self.FPS)
                out_t = tuh.convert(converted_back, tu1, 'm', self.FPS)
                self.assertAlmostEqual(value, out_t, delta=1000/self.FPS)  # up to 1 frame error


class TestVideoDocumentHelper(unittest.TestCase):
    def setUp(self):
        self.fps = 29.97
        self.mmif_obj = Mmif(validate=False)
        self.a_view = self.mmif_obj.new_view()
        self.video_doc = Document({
            "@type": "http://mmif.clams.ai/vocabulary/VideoDocument/v1",
            "properties": {
                "mime": "video",
                "id": "d1",
                "location": f"file://{pathlib.Path(__file__).parent}/black-2997fps.mp4"
            }
        })
        self.video_doc.add_property('fps', self.fps)
        self.mmif_obj.add_document(self.video_doc)

    def test_extract_mid_frame(self):
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=100, end=200, timeUnit='frame', document=self.video_doc.id)
        self.assertEqual(150, vdh.get_mid_framenum(self.mmif_obj, tf))
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=0, end=200, timeUnit='frame', document=self.video_doc.id)
        self.assertEqual(100, vdh.get_mid_framenum(self.mmif_obj, tf))
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=0, end=3, timeUnit='seconds', document=self.video_doc.id)
        self.assertEqual(vdh.convert(1.5, 's', 'f', self.fps), vdh.get_mid_framenum(self.mmif_obj, tf))

    @pytest.mark.filterwarnings('ignore::DeprecationWarning')
    def test_extract_representative_frame(self):
        tp = self.a_view.new_annotation(AnnotationTypes.TimePoint, timePoint=1500, timeUnit='milliseconds', document=self.video_doc.id)
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=1000, end=2000, timeUnit='milliseconds', document=self.video_doc.id)
        tf.add_property('representatives', [tp.id])
        rep_frame_num = vdh.get_representative_framenum(self.mmif_obj, tf)
        expected_frame_num = vdh.millisecond_to_framenum(self.video_doc, tp.get_property('timePoint'))
        self.assertEqual(expected_frame_num, rep_frame_num)
        # and should work even if no representatives are provided
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=1000, end=2000, timeUnit='milliseconds', document=self.video_doc.id)
        self.assertEqual(vdh.get_representative_framenum(self.mmif_obj, tf), vdh.get_mid_framenum(self.mmif_obj, tf))
        # check there is an error if there is a representative referencing a timepoint that does not exist
        tf.add_property('representatives', ['fake_tp_id'])
        with pytest.raises(ValueError):
            vdh.get_representative_framenum(self.mmif_obj, tf)

    def test_get_framerate(self):
        self.assertAlmostEqual(29.97, vdh.get_framerate(self.video_doc), places=0)

    @pytest.mark.filterwarnings('ignore::DeprecationWarning')
    def test_frames_to_seconds(self):
        self.assertAlmostEqual(3.337, vdh.framenum_to_second(self.video_doc, 100), places=0)

    @pytest.mark.filterwarnings('ignore::DeprecationWarning')
    def test_frames_to_milliseconds(self):
        self.assertAlmostEqual(3337.0, vdh.framenum_to_millisecond(self.video_doc, 100), places=0)

    @pytest.mark.filterwarnings('ignore::DeprecationWarning')
    def test_seconds_to_frames(self):
        self.assertAlmostEqual(100, vdh.second_to_framenum(self.video_doc, 3.337), places=0)

    @pytest.mark.filterwarnings('ignore::DeprecationWarning')
    def test_milliseconds_to_frames(self):
        self.assertAlmostEqual(100, vdh.millisecond_to_framenum(self.video_doc, 3337.0), places=0)

    @pytest.mark.filterwarnings('ignore::DeprecationWarning')
    def test_convert_roundtrip(self):
        # ms for 1 frame
        tolerance = 1000 / self.video_doc.get_property('fps')
        for ms in [1000, 1234, 4321, 44444, 789789]:
            m2f = vdh.millisecond_to_framenum(self.video_doc, ms)
            m2f2m = vdh.framenum_to_millisecond(self.video_doc, m2f)
            self.assertAlmostEqual(ms, m2f2m, delta=tolerance)

    @pytest.mark.filterwarnings('ignore::DeprecationWarning')
    def test_sample_frames(self):
        s_frame = vdh.second_to_framenum(self.video_doc, 3)
        e_frame = vdh.second_to_framenum(self.video_doc, 5.5)
        # note that int(29.97) = 29
        self.assertEqual(3, len(vdh.sample_frames(s_frame, e_frame, self.fps)))
        s_frame = vdh.second_to_framenum(self.video_doc, 3)
        e_frame = vdh.second_to_framenum(self.video_doc, 5)
        self.assertEqual(1, len(vdh.sample_frames(s_frame, e_frame, 60)))

    def test_deprecated_framenum_helpers_warn(self):
        # each fnum-leaking helper should emit DeprecationWarning pointing at issue #379
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.framenum_to_second(self.video_doc, 100)
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.framenum_to_millisecond(self.video_doc, 100)
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.second_to_framenum(self.video_doc, 1)
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.millisecond_to_framenum(self.video_doc, 1000)
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.sample_frames(0, 10, 1)

    def test_convert_timepoint(self):
        timepoint_ann = self.a_view.new_annotation(AnnotationTypes.BoundingBox, timePoint=3, timeUnit='second',
                                                   document='d1')
        self.assertEqual(vdh.convert(3, 's', 'f', self.fps), vdh.convert_timepoint(self.mmif_obj, timepoint_ann, 'f'))

    def test_convert_timeframe(self):
        self.a_view.metadata.new_contain(AnnotationTypes.TimeFrame, timeUnit='frame', document=self.video_doc.id)
        timeframe_ann = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=100, end=200)
        for times in zip((3.337, 6.674), vdh.convert_timeframe(self.mmif_obj, timeframe_ann, 's')):
            self.assertAlmostEqual(*times, places=0)

    @pytest.mark.filterwarnings('ignore::DeprecationWarning')
    def test_extract_frames_as_images(self):
        frame_list = [5, 10, 15]
        target_images = vdh.extract_frames_as_images(self.video_doc, frame_list, as_PIL=False)
        self.assertEqual(3, len(target_images))
        # check if the extract_frames_as_images destroy the input frame list
        self.assertEqual(3, len(frame_list))
        # check return empty list if the frame list is empty
        empty_flist = []
        empty_target_images = vdh.extract_frames_as_images(self.video_doc, empty_flist, as_PIL=False)
        self.assertEqual([], empty_target_images)
        # check there is an error if there is a frame in the list that does not exist
        tot_fcount = self.video_doc.get_property('frameCount')
        frame_list.append(tot_fcount + 1)
        new_target_images = vdh.extract_frames_as_images(self.video_doc, frame_list, as_PIL=False)
        self.assertEqual(4, len(frame_list))
        self.assertEqual(3, len(new_target_images))

    def test_open_container(self):
        # open_container sets fps/frameCount/duration as informational props
        vd = Document({
            "@type": "http://mmif.clams.ai/vocabulary/VideoDocument/v1",
            "properties": {
                "mime": "video",
                "id": "o1",
                "location": f"file://{pathlib.Path(__file__).parent}/black-2997fps.mp4",
            }
        })
        c = vdh.open_container(vd)
        try:
            self.assertAlmostEqual(29.97, vd.get_property('fps'), places=1)
            self.assertGreater(vd.get_property('frameCount'), 0)
            self.assertGreater(vd.get_property('duration'), 0)
        finally:
            c.close()

    def test_sample_timepoints(self):
        # half-open interval; step in ms
        self.assertEqual([0, 100, 200, 300, 400],
                         vdh.sample_timepoints(0, 500, 100))
        # empty when step overshoots
        self.assertEqual([0], vdh.sample_timepoints(0, 100, 200))
        # negative or zero step is a programmer error
        with pytest.raises(ValueError):
            vdh.sample_timepoints(0, 100, 0)
        with pytest.raises(ValueError):
            vdh.sample_timepoints(0, 100, -10)

    def test_extract_timepoints_as_images(self):
        # basic: three distinct timepoints
        ms_list = [1000, 2000, 3000]
        imgs = vdh.extract_timepoints_as_images(
            self.video_doc, ms_list, as_PIL=False)
        self.assertEqual(3, len(imgs))
        # empty input
        self.assertEqual(
            [], vdh.extract_timepoints_as_images(self.video_doc, []))
        # duplicates preserved in input order
        dup_ms = [500, 250, 500, 750, 250]
        dup_imgs = vdh.extract_timepoints_as_images(self.video_doc, dup_ms)
        self.assertEqual(5, len(dup_imgs))

    def _make_timepoints(self, count):
        # Explicit aid avoids a pre-existing clams-vocabulary / mmif-python
        # compat path (`at_type.get_prefix()`) that is broken in this env
        # and is not related to this PR.
        tps = []
        for i in range(count):
            tp = self.a_view.new_annotation(
                AnnotationTypes.TimePoint, aid=f'tp_{i}',
                timePoint=i * 100, timeUnit='milliseconds',
                document=self.video_doc.id)
            tps.append(tp)
        return tps

    def test_sample_all_timepoints_ms(self):
        tps = self._make_timepoints(10)
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            targets=[tp.id for tp in tps])

        ms_list = vdh._sample_all_timepoints_ms(self.mmif_obj, parent)
        self.assertEqual([i * 100 for i in range(10)], ms_list)

        # start/end fallback (no targets): sampled at the stream's frame rate
        parent2 = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_1',
            start=0, end=1000, timeUnit='milliseconds',
            document=self.video_doc.id)
        ms_list2 = vdh._sample_all_timepoints_ms(self.mmif_obj, parent2)
        # 30 frames in 1000ms at 29.97fps (step ≈ 33.37ms)
        self.assertEqual(30, len(ms_list2))
        self.assertEqual(0, ms_list2[0])
        self.assertLess(ms_list2[-1], 1000)

    def test_sample_representatives_timepoints_ms(self):
        tps = self._make_timepoints(10)
        reps = [tps[2].id, tps[5].id, tps[8].id]
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            targets=[tp.id for tp in tps],
            representatives=reps)

        ms_list = vdh._sample_representatives_timepoints_ms(
            self.mmif_obj, parent)
        self.assertEqual([200, 500, 800], ms_list)

        # no representatives → empty (skip)
        parent2 = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_1',
            targets=[tp.id for tp in tps])
        self.assertEqual(
            [], vdh._sample_representatives_timepoints_ms(
                self.mmif_obj, parent2))

    def test_sample_single_timepoint_ms(self):
        tps = self._make_timepoints(10)
        reps = [tps[2].id, tps[5].id, tps[8].id]
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            targets=[tp.id for tp in tps],
            representatives=reps)

        # middle representative (index 1 of 3 → tps[5] → 500ms)
        self.assertEqual(
            [500],
            vdh._sample_single_timepoint_ms(self.mmif_obj, parent))

        # start/end fallback midpoint
        parent2 = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_1',
            start=100, end=500, timeUnit='milliseconds',
            document=self.video_doc.id)
        self.assertEqual(
            [300],
            vdh._sample_single_timepoint_ms(self.mmif_obj, parent2))

    def test_pts_offset_regression(self):
        # regression for https://github.com/clamsproject/mmif-python/issues/379
        # on a container with non-zero PTS start offset, requesting a
        # timepoint equal to the first frame's actual PTS must return that
        # first frame, not the second one.
        import av
        fixture = pathlib.Path(__file__).parent / 'testsrc-2997fps-ptsoffset.mp4'
        vd = Document({
            "@type": "http://mmif.clams.ai/vocabulary/VideoDocument/v1",
            "properties": {
                "mime": "video",
                "id": "p1",
                "location": f"file://{fixture}",
            }
        })

        # ground truth: map (pixel-bytes hash) → pts for every frame
        container = av.open(str(fixture))
        stream = container.streams.video[0]
        tb = float(stream.time_base)
        pts_by_hash = {}
        for frame in container.decode(stream):
            if frame.pts is None:
                continue
            pts_by_hash[hash(frame.to_ndarray(format='bgr24').tobytes())] \
                = frame.pts
        container.close()

        # requested 33ms should resolve to the actual PTS-equivalent frame
        # (start_time is ~33ms; the first frame's PTS is nearest 33ms)
        imgs = vdh.extract_timepoints_as_images(vd, [33], as_PIL=False)
        self.assertEqual(1, len(imgs))
        got_pts = pts_by_hash.get(hash(imgs[0].tobytes()))
        self.assertIsNotNone(got_pts)
        got_ms = got_pts * tb * 1000
        frame_dur_ms = 1000 / 29.97
        self.assertLessEqual(abs(got_ms - 33),
                             frame_dur_ms / 2 + 1.0)

        # differential: the deprecated cv2 path returns a DIFFERENT frame
        # (off by one) for the same requested timepoint → this confirms
        # the fix.
        import warnings as _w
        with _w.catch_warnings():
            _w.simplefilter('ignore', DeprecationWarning)
            fnum = vdh.millisecond_to_framenum(vd, 33)
            old_img = vdh.extract_frames_as_images(vd, [fnum])[0]
        old_pts = pts_by_hash.get(hash(old_img.tobytes()))
        self.assertNotEqual(got_pts, old_pts,
                            'cv2 and PyAV paths should disagree on '
                            'PTS-offset videos')


class TestSequenceHelper(unittest.TestCase):

    def test_validate_labelset(self):
        mmif_obj = Mmif(validate=False)
        view = mmif_obj.new_view()
        anns = [view.new_annotation(AnnotationTypes.TimePoint, labelset=['a', 'b', 'c']) for _ in range(3)]
        self.assertTrue(sqh.validate_labelset(anns))
        anns.append(view.new_annotation(AnnotationTypes.TimePoint, labelset=['a', 'b', 'c', 'd']))
        with pytest.raises(ValueError):
            self.assertFalse(sqh.validate_labelset(anns))
        anns.pop()
        anns.append(view.new_annotation(AnnotationTypes.TimePoint))
        with pytest.raises(KeyError):
            self.assertFalse(sqh.validate_labelset(anns))

    def test_build_remapper(self):
        self.assertEqual({'a': 'a', 'b': 'b', 'c': 'c', 'd': 'd', 'e': 'e', 'f': 'f'},
                         sqh.build_label_remapper(list('abcdef'), {}))
        self.assertEqual({'a': 1, 'b': 2, 'c': 1, 'd': '-', 'e': '-', 'f': '-'},
                         sqh.build_label_remapper(list('abcdef'), {'a': 1, 'b': 2, 'c': 1}))

    def test_build_score_lists(self):
        c1 = {'a': 0.1, 'b': 0.2, 'c': 0.3}
        c2 = {'a': 0.6, 'b': 0.5, 'c': 0.4}
        remap = {'a': 'x', 'b': 'y', 'c': 'x'}
        lblmap, scores = sqh.build_score_lists([c1, c2], remap)
        self.assertEqual(2, len(scores.shape))
        self.assertEqual(2, scores.shape[0])
        self.assertEqual(2, scores.shape[1])
        self.assertEqual({'x': [0.3, 0.6], 'y': [0.2, 0.5]}, {lbl: list(scores[idx]) for lbl, idx in lblmap.items()})
        _, scores = sqh.build_score_lists([c1, c2], remap, score_remap_op=min)
        self.assertEqual({'x': [0.1, 0.4], 'y': [0.2, 0.5]}, {lbl: list(scores[idx]) for lbl, idx in lblmap.items()})

    def test_width_based_smoothing(self):
        scores = [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1],
        # cannot pass non-positive threshold for sequence sizes
        with pytest.raises(ValueError):
            sqh.smooth_outlying_short_intervals(scores, 1, 0)
        with pytest.raises(ValueError):
            sqh.smooth_outlying_short_intervals(scores, 0, 1)
        with pytest.raises(ValueError):
            sqh.smooth_outlying_short_intervals(scores, 0, 0)
        self.assertEqual([(1, 13), (19, 20)],
                         sqh.smooth_outlying_short_intervals(scores, 1, 4))
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        self.assertEqual([(1, 7)],
                         sqh.smooth_outlying_short_intervals(scores, 4, 2))
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
        self.assertEqual([(1, 13)],
                         sqh.smooth_outlying_short_intervals(scores, 4, 4))
        # special test case for not trimming short end peaks adjacent to short gaps
        scores = [1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1]
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        self.assertEqual([(0, 7), (11, 20)],
                         sqh.smooth_outlying_short_intervals(scores, 4, 4))
        # special test case for stitching only mode
        scores = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1]
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1],
        self.assertEqual([(3, 7), (11, 15), (18, 20)],
                         sqh.smooth_outlying_short_intervals(scores, 1, 1))


class TestTextDocHelper(unittest.TestCase):
    mmif_obj = Mmif(mmif_examples.MMIF_EXAMPLES['everything'])

    @pytest.mark.skip("The only valid test cases come from kaldi app which annotates wrong property")
    def test_slice_text(self):
        sliced_text_full_overlap = tdh.slice_text(self.mmif_obj, 11500, 14600)
        sliced_text_partial_overlap = tdh.slice_text(self.mmif_obj, 7, 10, unit="seconds")
        no_sliced_text = tdh.slice_text(self.mmif_obj, 0, 5000)
        full_sliced_text = tdh.slice_text(self.mmif_obj, 0, 22, unit="seconds")
        self.assertEqual("In the nineteen eighties ,", sliced_text_full_overlap)
        self.assertEqual("is Jim Lehrer with the NewsHour", sliced_text_partial_overlap)
        self.assertEqual("", no_sliced_text)
        self.assertEqual(
            "Hello , this is Jim Lehrer with the NewsHour on PBS . "
            "In the nineteen eighties , barking dogs have increasingly become a problem in urban areas .",
            full_sliced_text)


class TestWorkflowHelper(unittest.TestCase):

    def setUp(self) -> None:
        self.maxDiff = None
        self.basic_mmif = Mmif(
            '{"metadata": {"mmif": "http://mmif.clams.ai/1.0.0"}, "documents": [{"@type": "http://mmif.clams.ai/vocabulary/VideoDocument/v1", "properties": {"id": "d1", "mime": "video/mp4", "location": "file:///test/video.mp4"}}], "views": []}'
        )

    def create_temp_mmif_file(self, mmif_obj):
        """Helper to create a temporary MMIF file."""
        tmp = tempfile.NamedTemporaryFile(mode='w', suffix='.mmif', delete=False)
        if isinstance(mmif_obj, Mmif):
            content_to_write = mmif_obj.serialize(pretty=False)
        else:
            content_to_write = json.dumps(mmif_obj)
        tmp.write(content_to_write)
        tmp.close()
        return tmp.name

    def test_split_appname_appversion(self):
        app_name, app_version = wfh._split_appname_appversion("http://apps.clams.ai/test-app/v1.0.0")
        self.assertEqual(app_name, "test-app")
        self.assertEqual(app_version, "v1.0.0")

    def test_generate_param_hash(self):
        params = {"param1": "value1", "param2": 42}
        hash1 = wfh.generate_param_hash(params)
        hash2 = wfh.generate_param_hash(params)
        self.assertEqual(hash1, hash2)
        params_reversed = {"param2": 42, "param1": "value1"}
        hash3 = wfh.generate_param_hash(params_reversed)
        self.assertEqual(hash1, hash3)

    def test_generate_workflow_identifier_grouped(self):
        view1 = self.basic_mmif.new_view()
        view1.metadata.app = "http://apps.clams.ai/app1/v1.0.0"
        view1.metadata.timestamp = "2024-01-01T12:00:00Z"
        view2 = self.basic_mmif.new_view()
        view2.metadata.app = "http://apps.clams.ai/app1/v1.0.0"
        view2.metadata.timestamp = "2024-01-01T12:00:00Z"
        view3 = self.basic_mmif.new_view()
        view3.metadata.app = "http://apps.clams.ai/app2/v2.0.0"
        view3.metadata.timestamp = "2024-01-01T12:01:00Z"
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        import os
        try:
            workflow_id = wfh.generate_workflow_identifier(tmp_file)
            segments = workflow_id.split('/')
            self.assertEqual(len(segments), 7)
            self.assertIn('app1', segments[1])
            self.assertIn('app2', segments[4])
        finally:
            os.unlink(tmp_file)

    def test_generate_workflow_identifier_with_mmif_object(self):
        """Test that generate_workflow_identifier accepts Mmif objects directly."""
        import os

        # Test with Mmif object directly
        workflow_id_from_obj = wfh.generate_workflow_identifier(self.basic_mmif)

        # Test with file path - should produce the same result
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            workflow_id_from_file = wfh.generate_workflow_identifier(tmp_file)
            self.assertEqual(workflow_id_from_obj, workflow_id_from_file)
        finally:
            os.unlink(tmp_file)

    def test_read_mmif_from_path(self):
        """Test the _read_mmif_from_path helper function."""

        # Test with Mmif object - should return as-is
        result = wfh._read_mmif_from_path(self.basic_mmif)
        self.assertIs(result, self.basic_mmif)

        # Test with file path string
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result_from_str = wfh._read_mmif_from_path(tmp_file)
            self.assertIsInstance(result_from_str, Mmif)
            self.assertEqual(result_from_str.serialize(pretty=False), self.basic_mmif.serialize(pretty=False))

            # Test with Path object
            result_from_path = wfh._read_mmif_from_path(Path(tmp_file))
            self.assertIsInstance(result_from_path, Mmif)
            self.assertEqual(result_from_path.serialize(pretty=False), self.basic_mmif.serialize(pretty=False))
        finally:
            os.unlink(tmp_file)

        # Test with invalid input
        with pytest.raises(ValueError):
            wfh._read_mmif_from_path(12345)

    def test_describe_single_mmif_with_mmif_object(self):
        """Test that describe_single_mmif accepts Mmif objects directly."""
        import os

        # Test with Mmif object directly
        result_from_obj = wfh.describe_single_mmif(self.basic_mmif)

        # Test with file path - should produce the same result
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result_from_file = wfh.describe_single_mmif(tmp_file)
            self.assertEqual(result_from_obj, result_from_file)
            
            # Validate that the output conforms to the SingleMmifDesc Pydantic model
            # If validation succeeds, all required fields with correct aliases are present
            validated = wfh.SingleMmifDesc.model_validate(result_from_obj)
            # Can assert on the validated object's attributes if needed
            self.assertIsNotNone(validated.workflow_id)
            self.assertIsNotNone(validated.stats)
            self.assertIsNotNone(validated.apps)
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_empty(self):
        """Test describe_single_mmif with an empty MMIF (no views)."""
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 0)
            self.assertEqual(len(validated.apps), 0)
            self.assertEqual(validated.stats.annotation_count_by_type, {})
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_one_app(self):
        """Test describe_single_mmif with a single app execution."""
        view = self.basic_mmif.new_view()
        view.metadata.app = "http://apps.clams.ai/test-app/v1.0.0"
        view.metadata.timestamp = "2024-01-01T12:00:00Z"
        view.metadata.appProfiling = {"runningTime": "0:00:01.234"}
        view.new_annotation(AnnotationTypes.TimeFrame)
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 1)
            self.assertEqual(len(validated.apps), 1)
            app_exec = validated.apps[0]
            self.assertEqual(app_exec.app, view.metadata.app)
            self.assertEqual(app_exec.view_ids, [view.id])
            self.assertEqual(app_exec.app_profiling.running_time_ms, 1234)
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_one_app_two_views(self):
        """Test describe_single_mmif with one app execution producing two views."""
        view1 = self.basic_mmif.new_view()
        view1.metadata.app = "http://apps.clams.ai/test-app/v1.0.0"
        view1.metadata.timestamp = "2024-01-01T12:00:00Z"
        view1.new_annotation(AnnotationTypes.TimeFrame)
        view2 = self.basic_mmif.new_view()
        view2.metadata.app = "http://apps.clams.ai/test-app/v1.0.0"
        view2.metadata.timestamp = "2024-01-01T12:00:00Z"
        view2.new_annotation(AnnotationTypes.TimeFrame)
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 1)
            self.assertEqual(len(validated.apps), 1)
            app_exec = validated.apps[0]
            self.assertEqual(app_exec.view_ids, [view1.id, view2.id])
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_error_view(self):
        """Test describe_single_mmif with a view containing an error."""
        view = self.basic_mmif.new_view()
        view.metadata.app = "http://apps.clams.ai/test-app/v1.0.0"
        view.metadata.timestamp = "2024-01-01T12:00:00Z"
        view.metadata.error = {"message": "Something went wrong"}
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 0)
            self.assertEqual(len(validated.apps), 0)
            self.assertEqual(len(validated.stats.error_views), 1)
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_with_unassigned_views(self):
        """Test describe_single_mmif with views that cannot be grouped."""
        import unittest.mock
        raw_mmif = json.loads(self.basic_mmif.serialize())
        raw_mmif['views'].append({'id': 'v1', 'metadata': {'app': 'http://apps.clams.ai/app1/v1.0.0', 'timestamp': '2024-01-01T12:00:00Z'}, 'annotations': []})
        raw_mmif['views'].append({'id': 'v2', 'metadata': {'app': 'http://apps.clams.ai/app2/v2.0.0'}, 'annotations': []})
        raw_mmif['views'].append({'id': 'v3', 'metadata': {'timestamp': '2024-01-01T12:01:00Z', 'app': ''}, 'annotations': []})
        tmp_file = self.create_temp_mmif_file(raw_mmif)
        try:
            with unittest.mock.patch('jsonschema.validators.validate'):
                result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 1)
            self.assertEqual(len(validated.apps), 2)
            special_entry = validated.apps[-1]
            self.assertEqual(special_entry.app, 'http://apps.clams.ai/non-existing-app/v1')
            self.assertEqual(len(special_entry.view_ids), 2)
            self.assertIn('v2', special_entry.view_ids)
            self.assertIn('v3', special_entry.view_ids)
        finally:
            os.unlink(tmp_file)

    def test_describe_collection_empty(self):
        """Test describe_mmif_collection with an empty directory."""
        dummy_dir = 'dummy_mmif_collection'
        os.makedirs(dummy_dir, exist_ok=True)
        try:
            output = wfh.describe_mmif_collection(dummy_dir)
            # Validate using Pydantic model
            validated = wfh.CollectionMmifDesc.model_validate(output)
            self.assertEqual(validated.mmif_count_by_status.total, 0)
            self.assertEqual(len(validated.workflows), 0)
        finally:
            os.rmdir(dummy_dir)

    def test_describe_collection_with_files(self):
        """Test describe_mmif_collection with MMIF files."""
        dummy_dir = 'dummy_mmif_collection_with_files'
        os.makedirs(dummy_dir, exist_ok=True)
        try:
            # Create two MMIF files in the directory
            for i in range(2):
                tmp_file = os.path.join(dummy_dir, f'{i}.mmif')
                with open(tmp_file, 'w') as f:
                    f.write(self.basic_mmif.serialize())
            
            output = wfh.describe_mmif_collection(dummy_dir)
            
            # Validate structure using Pydantic model
            # If validation succeeds, all required fields with correct aliases are present
            validated = wfh.CollectionMmifDesc.model_validate(output)
            
            # Verify counts using validated object attributes
            self.assertEqual(validated.mmif_count_by_status.total, 2)
            self.assertIsInstance(validated.workflows, list)
        finally:
            import shutil
            shutil.rmtree(dummy_dir)


if __name__ == '__main__':
    unittest.main()
