import json
import os
import pathlib
import tempfile
import unittest
import warnings
from pathlib import Path
from unittest import mock

import pytest
from hypothesis import given
from hypothesis import strategies as st

from mmif import (
    AnnotationTypes, 
    Document, 
    DocumentTypes,
    Mmif
)
from mmif.utils import sequence_helper as sqh
from mmif.utils import text_document_helper as tdh
from mmif.utils import timeunit_helper as tuh
from mmif.utils import video_document_helper as vdh
from mmif.utils import workflow_helper as wfh
from tests import mmif_examples 


class TestTimeunitHelper(unittest.TestCase):
    FPS = 100  # 1 frame == 10 ms

    @given(st.integers(min_value=300, max_value=10000))
    def test_convert(self, value):
        # using hypothesis library, test time unit conversions 
        # four-way between second, millisecond, framenum, and isoformat 
        for tu1 in ['s', 'm', 'f', 'i']:
            for tu2 in ['s', 'm', 'f', 'i']:
                if tu1 == tu2:
                    continue
                # since the input (generated by hypothesis) is always integer/millisecond
                # I'm going to dual round-trip conversion
                # ms > tu1 > tu2 > tu1 > ms 
                # then see the ends are equal (enough)
                in_t = tuh.convert(value, 'm', tu1, self.FPS)
                converted = tuh.convert(in_t, tu1, tu2, self.FPS)
                converted_back = tuh.convert(converted, tu2, tu1, self.FPS)
                out_t = tuh.convert(converted_back, tu1, 'm', self.FPS)
                self.assertAlmostEqual(value, out_t, delta=1000/self.FPS)  # up to 1 frame error


@pytest.mark.filterwarnings('ignore::DeprecationWarning')
class TestVideoDocumentHelper(unittest.TestCase):
    def setUp(self):
        self.fps = 29.97
        self.mmif_obj = Mmif(validate=False)
        self.a_view = self.mmif_obj.new_view()
        self.video_doc = Document({
            "@type": DocumentTypes.VideoDocument,
            "properties": {
                "mime": "video",
                "id": "d1",
                "location": f"file://{pathlib.Path(__file__).parent}/black-2997fps.mp4"
            }
        })
        self.video_doc.add_property('fps', self.fps)
        self.mmif_obj.add_document(self.video_doc)

    def test_get_mid_framenum(self):
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=100, end=200, timeUnit='frame', document=self.video_doc.id)
        self.assertEqual(150, vdh.get_mid_framenum(self.mmif_obj, tf))
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=0, end=200, timeUnit='frame', document=self.video_doc.id)
        self.assertEqual(100, vdh.get_mid_framenum(self.mmif_obj, tf))
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=0, end=3, timeUnit='seconds', document=self.video_doc.id)
        self.assertEqual(vdh.convert(1.5, 's', 'f', self.fps), vdh.get_mid_framenum(self.mmif_obj, tf))

    def test_get_representative_framenum(self):
        tp = self.a_view.new_annotation(AnnotationTypes.TimePoint, timePoint=1500, timeUnit='milliseconds', document=self.video_doc.id)
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=1000, end=2000, timeUnit='milliseconds', document=self.video_doc.id)
        tf.add_property('representatives', [tp.id])
        rep_frame_num = vdh.get_representative_framenum(self.mmif_obj, tf)
        expected_frame_num = vdh.millisecond_to_framenum(self.video_doc, tp.get_property('timePoint'))
        self.assertEqual(expected_frame_num, rep_frame_num)
        # and should work even if no representatives are provided
        tf = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=1000, end=2000, timeUnit='milliseconds', document=self.video_doc.id)
        self.assertEqual(vdh.get_representative_framenum(self.mmif_obj, tf), vdh.get_mid_framenum(self.mmif_obj, tf))
        # check there is an error if there is a representative referencing a timepoint that does not exist
        tf.add_property('representatives', ['fake_tp_id'])
        with pytest.raises(ValueError):
            vdh.get_representative_framenum(self.mmif_obj, tf)

    def test_get_framerate(self):
        self.assertAlmostEqual(29.97, vdh.get_framerate(self.video_doc), places=0)

    def test_get_framerate_without_cached_property(self):
        # without an fps-like property, the rate comes from the container
        fixture = pathlib.Path(__file__).parent / 'black-2997fps.mp4'
        vd = Document({
            "@type": DocumentTypes.VideoDocument,
            "properties": {"mime": "video", "id": "r1",
                           "location": f"file://{fixture}"},
        })
        self.assertAlmostEqual(29.97, vdh.get_framerate(vd), places=1)
        # any of the accepted spellings is honored without opening the file
        for key in ('frameRate', 'frames_per_second', 'frame-per-second'):
            with self.subTest(key=key):
                aliased = Document({
                    "@type": DocumentTypes.VideoDocument,
                    "properties": {"mime": "video", "id": "r2",
                                   "location": "file:///nonexistent.mp4",
                                   key: 12.5},
                })
                self.assertEqual(12.5, vdh.get_framerate(aliased))

    def test_convert_roundtrip(self):
        # ms for 1 frame
        tolerance = 1000 / self.video_doc.get_property('fps')
        for ms in [1000, 1234, 4321, 44444, 789789]:
            m2f = vdh.millisecond_to_framenum(self.video_doc, ms)
            m2f2m = vdh.framenum_to_millisecond(self.video_doc, m2f)
            self.assertAlmostEqual(ms, m2f2m, delta=tolerance)

    def test_sample_frames(self):
        s_frame = vdh.second_to_framenum(self.video_doc, 3)
        e_frame = vdh.second_to_framenum(self.video_doc, 5.5)
        # note that int(29.97) = 29
        self.assertEqual(3, len(vdh.sample_frames(s_frame, e_frame, self.fps)))
        s_frame = vdh.second_to_framenum(self.video_doc, 3)
        e_frame = vdh.second_to_framenum(self.video_doc, 5)
        self.assertEqual(1, len(vdh.sample_frames(s_frame, e_frame, 60)))

    def test_deprecated_framenum_helpers_warn(self):
        # each fnum-leaking helper should emit DeprecationWarning pointing at issue #379
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.framenum_to_second(self.video_doc, 100)
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.framenum_to_millisecond(self.video_doc, 100)
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.second_to_framenum(self.video_doc, 1)
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.millisecond_to_framenum(self.video_doc, 1000)
        with pytest.warns(DeprecationWarning, match='#379'):
            vdh.sample_frames(0, 10, 1)

    def test_convert_timepoint(self):
        timepoint_ann = self.a_view.new_annotation(AnnotationTypes.BoundingBox, timePoint=3, timeUnit='second',
                                                   document='d1')
        self.assertEqual(vdh.convert(3, 's', 'f', self.fps), vdh.convert_timepoint(self.mmif_obj, timepoint_ann, 'f'))

    def test_convert_timeframe(self):
        self.a_view.metadata.new_contain(AnnotationTypes.TimeFrame, timeUnit='frame', document=self.video_doc.id)
        timeframe_ann = self.a_view.new_annotation(AnnotationTypes.TimeFrame, start=100, end=200)
        for times in zip((3.337, 6.674), vdh.convert_timeframe(self.mmif_obj, timeframe_ann, 's')):
            self.assertAlmostEqual(*times, places=0)

    def test_extract_frames_as_images(self):
        frame_list = [5, 10, 15]
        target_images = vdh.extract_frames_as_images(self.video_doc, frame_list, as_PIL=False)
        self.assertEqual(3, len(target_images))
        # check if the extract_frames_as_images destroy the input frame list
        self.assertEqual(3, len(frame_list))
        # check return empty list if the frame list is empty
        empty_flist = []
        empty_target_images = vdh.extract_frames_as_images(self.video_doc, empty_flist, as_PIL=False)
        self.assertEqual([], empty_target_images)
        # check there is an error if there is a frame in the list that does not exist
        tot_fcount = self.video_doc.get_property('frameCount')
        frame_list.append(tot_fcount + 1)
        new_target_images = vdh.extract_frames_as_images(self.video_doc, frame_list, as_PIL=False)
        self.assertEqual(4, len(frame_list))
        # the deprecated cv2 path keeps dropping unavailable frames, so its
        # list shortens where the current API would hold a `None` instead
        self.assertEqual(3, len(new_target_images))

    def test_deprecated_capture(self):
        fixture = pathlib.Path(__file__).parent / 'black-2997fps.mp4'
        vd = Document({
            "@type": DocumentTypes.VideoDocument,
            "properties": {"mime": "video", "id": "c1",
                           "location": f"file://{fixture}"},
        })
        with pytest.warns(DeprecationWarning, match='open_container'):
            capture = vdh.capture(vd)
        try:
            self.assertAlmostEqual(29.97, vd.get_property('fps'), places=1)
            self.assertGreater(vd.get_property('duration'), 0)
        finally:
            capture.release()

    def test_deprecated_frame_extractors(self):
        tp = self.a_view.new_annotation(
            AnnotationTypes.TimePoint, timePoint=1500,
            timeUnit='milliseconds', document=self.video_doc.id)
        tf = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, start=1000, end=2000,
            timeUnit='milliseconds', document=self.video_doc.id)
        tf.add_property('representatives', [tp.id])
        self.assertIsNotNone(vdh.extract_mid_frame(self.mmif_obj, tf))
        self.assertIsNotNone(
            vdh.extract_representative_frame(self.mmif_obj, tf))
        self.assertEqual(
            [vdh.millisecond_to_framenum(self.video_doc, 1500)],
            vdh.get_representative_framenums(self.mmif_obj, tf))

    def test_open_container(self):
        # open_container sets fps/frameCount/duration as informational props.
        # The webm case is a regression for issue #390: Matroska leaves the
        # per-stream `frames`/`duration` fields unset, so open_container must
        # fall back to the container-level duration instead of caching 0.
        for fixture in ('black-2997fps.mp4', 'black-2997fps.webm'):
            with self.subTest(fixture=fixture):
                path = pathlib.Path(__file__).parent / fixture
                vd = Document({
                    "@type": DocumentTypes.VideoDocument,
                    "properties": {"mime": "video", "id": "o1",
                                   "location": f"file://{path}"},
                })
                c = vdh.open_container(vd)
                try:
                    self.assertAlmostEqual(29.97, vd.get_property('fps'),
                                           places=1)
                    self.assertGreater(vd.get_property('frameCount'), 0)
                    self.assertGreater(vd.get_property('duration'), 0)
                finally:
                    c.close()

    def test_open_container_rejects_non_video(self):
        for bad_doc in (None, Document({
                "@type": "http://mmif.clams.ai/vocabulary/TextDocument/v1",
                "properties": {"mime": "text", "id": "t1"}})):
            with self.subTest(doc=bad_doc):
                with pytest.raises(ValueError):
                    vdh.open_container(bad_doc)

    def test_open_container_missing_file(self):
        # a missing file is not a broken file, and must stay distinguishable
        vd = Document({
            "@type": DocumentTypes.VideoDocument,
            "properties": {"mime": "video", "id": "m1",
                           "location": "file:///nonexistent-video.mp4"},
        })
        with pytest.raises(FileNotFoundError):
            vdh.open_container(vd)

    def test_sample_timepoints(self):
        # half-open interval; step in ms
        self.assertEqual([0, 100, 200, 300, 400],
                         vdh.sample_timepoints(0, 500, 100))
        # empty when step overshoots
        self.assertEqual([0], vdh.sample_timepoints(0, 100, 200))
        # negative or zero step is a programmer error
        with pytest.raises(ValueError):
            vdh.sample_timepoints(0, 100, 0)
        with pytest.raises(ValueError):
            vdh.sample_timepoints(0, 100, -10)

    def test_extract_images_from_timepoints(self):
        # in-range timepoints all yield an image, and nothing is reported
        ms_list = [1000, 2000, 3000]
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter('always')
            imgs = vdh.extract_images_from_timepoints(
                self.video_doc, ms_list, as_PIL=False)
        self.assertEqual(len(ms_list), len(imgs))
        self.assertTrue(all(img is not None for img in imgs))
        self.assertEqual([], [w for w in caught
                              if 'No image is available' in str(w.message)])
        # empty input
        self.assertEqual(
            [], vdh.extract_images_from_timepoints(self.video_doc, []))
        # duplicates yield the same image object at each repeated position
        dup_ms = [500, 250, 500, 750, 250]
        dup_imgs = vdh.extract_images_from_timepoints(self.video_doc, dup_ms)
        self.assertEqual(len(dup_ms), len(dup_imgs))
        self.assertIs(dup_imgs[0], dup_imgs[2])
        self.assertIs(dup_imgs[1], dup_imgs[4])

    def test_extract_images_as_PIL(self):
        Image = pytest.importorskip('PIL.Image')
        imgs = vdh.extract_images_from_timepoints(
            self.video_doc, [1000], as_PIL=True)
        self.assertIsInstance(imgs[0], Image.Image)

    def _make_timepoints(self, count):
        # Explicit aid avoids a pre-existing clams-vocabulary / mmif-python
        # compat path (`at_type.get_prefix()`) that is broken in this env
        # and is not related to this PR.
        tps = []
        for i in range(count):
            tp = self.a_view.new_annotation(
                AnnotationTypes.TimePoint, aid=f'tp_{i}',
                timePoint=i * 100, timeUnit='milliseconds',
                document=self.video_doc.id)
            tps.append(tp)
        return tps

    def test_sample_all_timepoint_pairs_ms(self):
        tps = self._make_timepoints(10)
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            targets=[tp.id for tp in tps])

        pairs = vdh._sample_all_timepoint_pairs_ms(self.mmif_obj, parent)
        # source IDs are the target TP ids; ms values match timePoints
        self.assertEqual(
            [(i * 100, tp.id) for i, tp in enumerate(tps)], pairs)

        # start/end fallback (no targets): sampled at the stream's frame
        # rate; source is None for each sampled point
        parent2 = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_1',
            start=0, end=1000, timeUnit='milliseconds',
            document=self.video_doc.id)
        pairs2 = vdh._sample_all_timepoint_pairs_ms(self.mmif_obj, parent2)
        # 30 frames in 1000ms at 29.97fps (step ≈ 33.37ms)
        self.assertEqual(30, len(pairs2))
        self.assertEqual((0, None), pairs2[0])
        self.assertTrue(all(src is None for _, src in pairs2))
        self.assertLess(pairs2[-1][0], 1000)

    def test_sample_representatives_timepoint_pairs_ms(self):
        tps = self._make_timepoints(10)
        reps = [tps[2].id, tps[5].id, tps[8].id]
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            targets=[tp.id for tp in tps],
            representatives=reps)

        pairs = vdh._sample_representatives_timepoint_pairs_ms(
            self.mmif_obj, parent)
        self.assertEqual(
            [(200, reps[0]), (500, reps[1]), (800, reps[2])], pairs)

        # no representatives → empty (skip)
        parent2 = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_1',
            targets=[tp.id for tp in tps])
        self.assertEqual(
            [], vdh._sample_representatives_timepoint_pairs_ms(
                self.mmif_obj, parent2))

    def test_sample_single_timepoint_pair_ms(self):
        tps = self._make_timepoints(10)
        reps = [tps[2].id, tps[5].id, tps[8].id]
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            targets=[tp.id for tp in tps],
            representatives=reps)

        # middle representative (index 1 of 3 → tps[5] → 500ms, source=reps[1])
        self.assertEqual(
            [(500, reps[1])],
            vdh._sample_single_timepoint_pair_ms(self.mmif_obj, parent))

        # start/end fallback midpoint: source is None
        parent2 = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_1',
            start=100, end=500, timeUnit='milliseconds',
            document=self.video_doc.id)
        self.assertEqual(
            [(300, None)],
            vdh._sample_single_timepoint_pair_ms(self.mmif_obj, parent2))

    def test_extract_images_by_count(self):
        tps = self._make_timepoints(10)
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            targets=[tp.id for tp in tps])

        # bare form: returns just images
        imgs = vdh.extract_images_by_count(self.mmif_obj, parent, fraction=0.3)
        self.assertEqual(3, len(imgs))

        # missing 'targets' raises ValueError (bare delegates through
        # _with_sources)
        no_targets = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_no',
            start=0, end=100, timeUnit='milliseconds',
            document=self.video_doc.id)
        with pytest.raises(ValueError):
            vdh.extract_images_by_count(self.mmif_obj, no_targets)

    def test_extract_images_by_count_with_sources(self):
        tps = self._make_timepoints(10)
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            targets=[tp.id for tp in tps])

        imgs, ids = vdh.extract_images_by_count_with_sources(
            self.mmif_obj, parent, fraction=0.5)
        self.assertEqual(len(imgs), len(ids))
        self.assertEqual(5, len(imgs))
        # source IDs are a subset of the input targets, in order
        self.assertEqual(ids, sorted(ids, key=[t.id for t in tps].index))
        for tid in ids:
            self.assertIn(tid, [t.id for t in tps])

        # empty targets → empty parallel lists
        empty = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_empty', targets=[])
        self.assertEqual(
            ([], []),
            vdh.extract_images_by_count_with_sources(self.mmif_obj, empty))

    def test_extract_images_by_mode_with_sources_reps(self):
        tps = self._make_timepoints(10)
        reps = [tps[2].id, tps[5].id, tps[8].id]
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            targets=[tp.id for tp in tps],
            representatives=reps)

        imgs, sources = vdh.extract_images_by_mode_with_sources(
            self.mmif_obj, parent, mode=vdh.SamplingMode.REPRESENTATIVES)
        self.assertEqual(3, len(imgs))
        # all sources are TP IDs (str), not ms ints
        self.assertEqual(reps, sources)
        self.assertTrue(all(isinstance(s, str) for s in sources))

    def test_extract_images_by_mode_with_sources_single_fallback(self):
        # SINGLE mode without representatives → midpoint fallback,
        # source is the midpoint ms (int)
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            start=100, end=500, timeUnit='milliseconds',
            document=self.video_doc.id)
        imgs, sources = vdh.extract_images_by_mode_with_sources(
            self.mmif_obj, parent, mode=vdh.SamplingMode.SINGLE)
        self.assertEqual(1, len(imgs))
        self.assertEqual([300], sources)
        self.assertTrue(all(isinstance(s, int) for s in sources))

    def test_extract_images_by_mode_with_sources_all_fallback(self):
        # ALL mode without targets → stream-rate sampling, sources are
        # the sampled ms ints
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0',
            start=0, end=200, timeUnit='milliseconds',
            document=self.video_doc.id)
        imgs, sources = vdh.extract_images_by_mode_with_sources(
            self.mmif_obj, parent, mode=vdh.SamplingMode.ALL)
        self.assertEqual(len(imgs), len(sources))
        self.assertGreater(len(imgs), 0)
        self.assertTrue(all(isinstance(s, int) for s in sources))
        # the sources match the sampled ms values
        self.assertEqual(sorted(sources), sources)

    def test_renamed_helpers_emit_deprecation_warnings(self):
        # The three pre-rename names live as deprecation aliases that
        # delegate to the new names.
        with pytest.warns(DeprecationWarning, match='extract_images_from_timepoints'):
            vdh.extract_timepoints_as_images(self.video_doc, [500])

        tps = self._make_timepoints(4)
        parent = self.a_view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_dep',
            targets=[tp.id for tp in tps])
        with pytest.warns(DeprecationWarning, match='extract_images_by_count_with_sources'):
            vdh.extract_target_frames(self.mmif_obj, parent)

        with pytest.warns(DeprecationWarning, match='extract_images_by_mode'):
            vdh.extract_frames_by_mode(
                self.mmif_obj, parent, mode=vdh.SamplingMode.ALL)

    def test_pts_offset_regression(self):
        # regression for https://github.com/clamsproject/mmif-python/issues/379
        # on a container with non-zero PTS start offset, requesting a
        # timepoint equal to the first frame's actual PTS must return that
        # first frame, not the second one.
        import av
        fixture = pathlib.Path(__file__).parent / 'testsrc-2997fps-ptsoffset.mp4'
        vd = Document({
            "@type": DocumentTypes.VideoDocument,
            "properties": {
                "mime": "video",
                "id": "p1",
                "location": f"file://{fixture}",
            }
        })

        # ground truth: map (pixel-bytes hash) → pts for every frame
        container = av.open(str(fixture))
        stream = container.streams.video[0]
        tb = float(stream.time_base)
        pts_by_hash = {}
        for frame in container.decode(stream):
            if frame.pts is None:
                continue
            pts_by_hash[hash(frame.to_ndarray(format='bgr24').tobytes())] \
                = frame.pts
        container.close()

        # requested 33ms should resolve to the actual PTS-equivalent frame
        # (start_time is ~33ms; the first frame's PTS is nearest 33ms)
        imgs = vdh.extract_images_from_timepoints(vd, [33], as_PIL=False)
        self.assertEqual(1, len(imgs))
        got_pts = pts_by_hash.get(hash(imgs[0].tobytes()))
        self.assertIsNotNone(got_pts)
        got_ms = got_pts * tb * 1000
        frame_dur_ms = 1000 / 29.97
        self.assertLessEqual(abs(got_ms - 33),
                             frame_dur_ms / 2 + 1.0)

        # differential: the deprecated cv2 path returns a DIFFERENT frame
        # (off by one) for the same requested timepoint → this confirms
        # the fix.
        import warnings as _w
        with _w.catch_warnings():
            _w.simplefilter('ignore', DeprecationWarning)
            fnum = vdh.millisecond_to_framenum(vd, 33)
            old_img = vdh.extract_frames_as_images(vd, [fnum])[0]
        old_pts = pts_by_hash.get(hash(old_img.tobytes()))
        self.assertNotEqual(got_pts, old_pts,
                            'cv2 and PyAV paths should disagree on '
                            'PTS-offset videos')


class TestBrokenVideoDocument(unittest.TestCase):
    """
    Covers videos that hold fewer images than their container metadata
    promises (issue #400). A byte-truncated file surfaces differently per
    container and per cut position, so each path gets its own fixture.
    """

    fixtures_dir = pathlib.Path(__file__).parent

    @classmethod
    def setUpClass(cls):
        # fixtures are byte-identical for every test, so they are built once
        cls.tmpdir = tempfile.TemporaryDirectory()
        cls.addClassCleanup(cls.tmpdir.cleanup)
        tmp = pathlib.Path(cls.tmpdir.name)
        healthy_mp4 = cls.fixtures_dir / 'black-2997fps.mp4'
        faststart = tmp / 'faststart.mp4'
        cls._remux_faststart(healthy_mp4, faststart)
        cls.cuts = {
            # cut mid-packet: the mp4 demuxer hands the partial packet to the
            # decoder, which raises
            'unclean.mp4': (cls._truncate(faststart, tmp / 'unclean.mp4'),
                            True),
            # cut at a packet boundary: a clean EOF, indistinguishable from
            # the end of a healthy video
            'clean.mp4': (cls._truncate(faststart, tmp / 'clean.mp4',
                                        cls._clean_cut_offset(faststart)),
                          False),
            # Matroska drops the incomplete block, so any cut is clean
            'cut.webm': (cls._truncate(cls.fixtures_dir / 'black-2997fps.webm',
                                       tmp / 'cut.webm'),
                         False),
        }
        # `moov` sits at the end of the shipped fixtures, so a cut copy of the
        # original cannot be opened at all
        cls.trailing_moov = cls._truncate(healthy_mp4, tmp / 'moovend.mp4')
        # opens fine, holds no video stream; the realistic case is an audio
        # file registered as a VideoDocument, and a tiny prefix behaves alike
        cls.audio_only = cls._write_audio_only(tmp / 'audio.wav')
        cls.tiny = cls._truncate(faststart, tmp / 'tiny.mp4', 200)
        cls.healthy = healthy_mp4

    @staticmethod
    def _doc(path, aid='d1'):
        return Document({
            "@type": DocumentTypes.VideoDocument,
            "properties": {"mime": "video", "id": aid,
                           "location": f"file://{path}"}
        })

    @staticmethod
    def _remux_faststart(src, dst):
        # a cut copy of an mp4 is only decodable at all when the `moov` atom
        # sits at the front; the shipped fixtures carry it at the end
        import av
        faststart = {'movflags': 'faststart'}
        with av.open(str(src)) as inp, \
                av.open(str(dst), 'w', options=faststart) as out:
            in_stream = inp.streams.video[0]
            try:
                out_stream = out.add_stream_from_template(in_stream)
            except AttributeError:  # PyAV < 14
                out_stream = out.add_stream(template=in_stream)
            for packet in inp.demux(in_stream):
                if packet.dts is None:
                    continue
                packet.stream = out_stream
                out.mux(packet)

    @staticmethod
    def _write_audio_only(dst):
        import av
        import numpy as np
        rate = 8000
        with av.open(str(dst), 'w') as out:
            stream = out.add_stream('pcm_s16le', rate=rate, layout='mono')
            frame = av.AudioFrame.from_ndarray(
                np.zeros((1, rate), dtype='int16'), format='s16',
                layout='mono')
            frame.sample_rate = rate
            for packet in stream.encode(frame):
                out.mux(packet)
            for packet in stream.encode(None):
                out.mux(packet)
        return dst

    @staticmethod
    def _truncate(src, dst, nbytes=None):
        data = pathlib.Path(src).read_bytes()
        dst.write_bytes(data[:nbytes if nbytes else len(data) // 2])
        return dst

    @staticmethod
    def _clean_cut_offset(path):
        # end of the last complete packet before the halfway point
        import av
        half = pathlib.Path(path).stat().st_size // 2
        with av.open(str(path)) as container:
            stream = container.streams.video[0]
            return next(p.pos for p in container.demux(stream)
                        if p.pos is not None and p.pos >= half)

    @staticmethod
    def _last_decodable_ms(path):
        # ground truth for the assertions below, computed without vdh; the
        # decoder is flushed after an error, as vdh does, so that frames held
        # back for reordering count here too
        import av
        last = None

        def frames(container, stream):
            try:
                for packet in container.demux(stream):
                    yield from packet.decode()
            except av.error.FFmpegError:
                try:
                    yield from stream.codec_context.decode(None)
                except av.error.FFmpegError:
                    pass

        with av.open(str(path)) as container:
            stream = container.streams.video[0]
            for frame in frames(container, stream):
                if frame.pts is not None:
                    pts_ms = round(frame.pts * stream.time_base * 1000)
                    last = max(last or 0, pts_ms)
        return last

    @staticmethod
    def _missing_image_warnings(caught):
        # the module also emits unrelated warnings (e.g. vocabulary version
        # mismatches), and a single call must report missing images once
        return [str(w.message) for w in caught
                if 'No image is available' in str(w.message)]

    def _extract(self, doc, timepoints, **kwargs):
        with warnings.catch_warnings(record=True) as caught:
            warnings.simplefilter('always')
            images = vdh.extract_images_from_timepoints(
                doc, timepoints, **kwargs)
        return images, self._missing_image_warnings(caught)

    def _frame_ms(self, doc):
        return int(1000 / vdh.get_framerate(doc))

    def test_truncated_file_yields_none_past_last_frame(self):
        import av
        for name, (path, expect_decode_error) in self.cuts.items():
            with self.subTest(fixture=name):
                doc = self._doc(path)
                last_ok = self._last_decodable_ms(path)
                self.assertIsNotNone(last_ok,
                                     'fixture should decode at least once')
                frame_ms = self._frame_ms(doc)
                # the last decodable frame covers one frame duration, and
                # nothing beyond it; 2ms of slack absorbs ms/tick rounding
                timepoints = [0, last_ok, last_ok + frame_ms - 2,
                              last_ok + frame_ms + 2, 59000]
                images, messages = self._extract(doc, timepoints)
                self.assertEqual(len(timepoints), len(images))
                for i in (0, 1, 2):
                    self.assertIsNotNone(images[i], f'position {i}')
                self.assertIsNone(images[3])
                self.assertIsNone(images[4])
                # within the tolerance, the last frame itself is reused
                self.assertEqual(images[1].tobytes(), images[2].tobytes())
                self.assertEqual(1, len(messages))
                self.assertIn(vdh._media_check_hint(str(path)), messages[0])
                self.assertEqual(
                    expect_decode_error,
                    av.error.InvalidDataError.__name__ in messages[0])
                self.assertEqual(expect_decode_error,
                                 'first decoding error:' in messages[0])

    def test_missing_only_past_duration_is_not_flagged(self):
        # a file that merely ends is not suspect, even after a clean cut
        path, _ = self.cuts['cut.webm']
        doc = self._doc(path)
        vdh.open_container(doc).close()
        duration = doc.get_property('duration')
        images, messages = self._extract(doc, [duration + 10000])
        self.assertEqual([None], images)
        self.assertEqual(1, len(messages))
        self.assertNotIn(vdh._media_check_hint(str(path)), messages[0])

    def test_missing_before_and_past_duration_is_flagged(self):
        # the earliest missing timepoint decides, and both are listed
        path, _ = self.cuts['cut.webm']
        doc = self._doc(path)
        vdh.open_container(doc).close()
        duration = doc.get_property('duration')
        last_ok = self._last_decodable_ms(path)
        timepoints = [last_ok + 5000, duration + 10000]
        images, messages = self._extract(doc, timepoints)
        self.assertEqual([None, None], images)
        self.assertEqual(1, len(messages))
        self.assertIn(vdh._media_check_hint(str(path)), messages[0])
        self.assertIn(f'{timepoints[0]}ms, {timepoints[1]}ms', messages[0])

    def test_repeated_missing_timepoint_counts_positions(self):
        path, _ = self.cuts['cut.webm']
        images, messages = self._extract(self._doc(path), [59000] * 3)
        self.assertEqual([None, None, None], images)
        self.assertIn('for 3 timepoint(s)', messages[0])

    def test_missing_entry_with_as_PIL(self):
        Image = pytest.importorskip('PIL.Image')
        path, _ = self.cuts['cut.webm']
        images, _ = self._extract(self._doc(path), [0, 59000], as_PIL=True)
        self.assertIsInstance(images[0], Image.Image)
        self.assertIsNone(images[1])

    def test_tolerance_falls_back_to_stream_rate(self):
        # a frame may carry no duration of its own, in which case the same
        # tolerance must come from the stream frame rate
        class _NoDuration:
            def __init__(self, frame):
                self._frame = frame
                self.duration = None

            def __getattr__(self, name):
                return getattr(self._frame, name)

        real_decode_frames = vdh._decode_frames

        def stripped(container, stream, decode_errors):
            for frame in real_decode_frames(container, stream, decode_errors):
                yield _NoDuration(frame)

        doc = self._doc(self.healthy)
        vdh.open_container(doc).close()
        duration = doc.get_property('duration')
        with mock.patch.object(vdh, '_decode_frames', stripped):
            images, messages = self._extract(doc, [duration - 1])
        self.assertIsNotNone(images[0])
        self.assertEqual([], messages)

    def test_unopenable_files_raise_with_hint(self):
        cases = {'trailing moov': self.trailing_moov,
                 'audio only': self.audio_only,
                 'tiny prefix': self.tiny}
        for label, path in cases.items():
            with self.subTest(case=label):
                with pytest.raises(RuntimeError) as excinfo:
                    vdh.open_container(self._doc(path))
                self.assertIn(vdh._media_check_hint(str(path)),
                              str(excinfo.value))
        # get_framerate goes through open_container, so it reports the same way
        with pytest.raises(RuntimeError):
            vdh.get_framerate(self._doc(self.trailing_moov))

    def test_failed_seek_raises_with_hint(self):
        # PyAV containers are immutable extension types, so the failure is
        # injected through a proxy around the real container
        import av
        path, _ = self.cuts['cut.webm']
        doc = self._doc(path)

        class _SeekFails:
            def __init__(self, container):
                self._container = container

            def __getattr__(self, name):
                return getattr(self._container, name)

            def seek(self, *args, **kwargs):
                raise av.error.InvalidDataError(1094995529, 'seek failed')

        real_open_container = vdh.open_container

        def wrapped(video_document):
            return _SeekFails(real_open_container(video_document))

        with mock.patch.object(vdh, 'open_container', wrapped):
            with pytest.raises(RuntimeError) as excinfo:
                vdh.extract_images_from_timepoints(doc, [1000])
        self.assertIn(vdh._media_check_hint(str(path)), str(excinfo.value))
        self.assertIn('seek failed', str(excinfo.value))

    def test_empty_request_never_opens_the_file(self):
        doc = self._doc(self.trailing_moov)
        self.assertEqual([], vdh.extract_images_from_timepoints(doc, []))

    def test_none_stays_parallel_with_sources(self):
        # the breakage that motivated issue #400: apps pair images with
        # timepoints by list index
        mmif_obj = Mmif(validate=False)
        doc = self._doc(self.healthy)
        mmif_obj.add_document(doc)
        vdh.open_container(doc).close()
        duration = doc.get_property('duration')
        view = mmif_obj.new_view()
        tp_ids = []
        for i, ms in enumerate([1000, duration + 10000, duration + 20000]):
            tp = view.new_annotation(
                AnnotationTypes.TimePoint, aid=f'tp_{i}', timePoint=ms,
                timeUnit='milliseconds', document=doc.id)
            tp_ids.append(tp.id)
        time_frame = view.new_annotation(
            AnnotationTypes.TimeFrame, aid='tf_0', document=doc.id,
            timeUnit='milliseconds', start=1000, end=duration + 20000,
            targets=tp_ids, representatives=tp_ids)
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            by_mode = vdh.extract_images_by_mode_with_sources(
                mmif_obj, time_frame, mode=vdh.SamplingMode.REPRESENTATIVES)
            by_count = vdh.extract_images_by_count_with_sources(
                mmif_obj, time_frame, fraction=1.0)
        for label, (images, sources) in {'by_mode': by_mode,
                                         'by_count': by_count}.items():
            with self.subTest(entrypoint=label):
                self.assertEqual(tp_ids, list(sources))
                self.assertEqual(len(sources), len(images))
                self.assertIsNotNone(images[0])
                self.assertIsNone(images[1])
                self.assertIsNone(images[2])


class TestSequenceHelper(unittest.TestCase):

    def test_validate_labelset(self):
        mmif_obj = Mmif(validate=False)
        view = mmif_obj.new_view()
        anns = [view.new_annotation(AnnotationTypes.TimePoint, labelset=['a', 'b', 'c']) for _ in range(3)]
        self.assertTrue(sqh.validate_labelset(anns))
        anns.append(view.new_annotation(AnnotationTypes.TimePoint, labelset=['a', 'b', 'c', 'd']))
        with pytest.raises(ValueError):
            self.assertFalse(sqh.validate_labelset(anns))
        anns.pop()
        anns.append(view.new_annotation(AnnotationTypes.TimePoint))
        with pytest.raises(KeyError):
            self.assertFalse(sqh.validate_labelset(anns))

    def test_build_remapper(self):
        self.assertEqual({'a': 'a', 'b': 'b', 'c': 'c', 'd': 'd', 'e': 'e', 'f': 'f'},
                         sqh.build_label_remapper(list('abcdef'), {}))
        self.assertEqual({'a': 1, 'b': 2, 'c': 1, 'd': '-', 'e': '-', 'f': '-'},
                         sqh.build_label_remapper(list('abcdef'), {'a': 1, 'b': 2, 'c': 1}))

    def test_build_score_lists(self):
        c1 = {'a': 0.1, 'b': 0.2, 'c': 0.3}
        c2 = {'a': 0.6, 'b': 0.5, 'c': 0.4}
        remap = {'a': 'x', 'b': 'y', 'c': 'x'}
        lblmap, scores = sqh.build_score_lists([c1, c2], remap)
        self.assertEqual(2, len(scores.shape))
        self.assertEqual(2, scores.shape[0])
        self.assertEqual(2, scores.shape[1])
        self.assertEqual({'x': [0.3, 0.6], 'y': [0.2, 0.5]}, {lbl: list(scores[idx]) for lbl, idx in lblmap.items()})
        _, scores = sqh.build_score_lists([c1, c2], remap, score_remap_op=min)
        self.assertEqual({'x': [0.1, 0.4], 'y': [0.2, 0.5]}, {lbl: list(scores[idx]) for lbl, idx in lblmap.items()})

    def test_width_based_smoothing(self):
        scores = [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1],
        # cannot pass non-positive threshold for sequence sizes
        with pytest.raises(ValueError):
            sqh.smooth_outlying_short_intervals(scores, 1, 0)
        with pytest.raises(ValueError):
            sqh.smooth_outlying_short_intervals(scores, 0, 1)
        with pytest.raises(ValueError):
            sqh.smooth_outlying_short_intervals(scores, 0, 0)
        self.assertEqual([(1, 13), (19, 20)],
                         sqh.smooth_outlying_short_intervals(scores, 1, 4))
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        self.assertEqual([(1, 7)],
                         sqh.smooth_outlying_short_intervals(scores, 4, 2))
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
        self.assertEqual([(1, 13)],
                         sqh.smooth_outlying_short_intervals(scores, 4, 4))
        # special test case for not trimming short end peaks adjacent to short gaps
        scores = [1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1]
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        self.assertEqual([(0, 7), (11, 20)],
                         sqh.smooth_outlying_short_intervals(scores, 4, 4))
        # special test case for stitching only mode
        scores = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1]
        # idx = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        # res = [0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1],
        self.assertEqual([(3, 7), (11, 15), (18, 20)],
                         sqh.smooth_outlying_short_intervals(scores, 1, 1))


class TestTextDocHelper(unittest.TestCase):
    mmif_obj = Mmif(mmif_examples.MMIF_EXAMPLES['everything'])

    @pytest.mark.skip("The only valid test cases come from kaldi app which annotates wrong property")
    def test_slice_text(self):
        sliced_text_full_overlap = tdh.slice_text(self.mmif_obj, 11500, 14600)
        sliced_text_partial_overlap = tdh.slice_text(self.mmif_obj, 7, 10, unit="seconds")
        no_sliced_text = tdh.slice_text(self.mmif_obj, 0, 5000)
        full_sliced_text = tdh.slice_text(self.mmif_obj, 0, 22, unit="seconds")
        self.assertEqual("In the nineteen eighties ,", sliced_text_full_overlap)
        self.assertEqual("is Jim Lehrer with the NewsHour", sliced_text_partial_overlap)
        self.assertEqual("", no_sliced_text)
        self.assertEqual(
            "Hello , this is Jim Lehrer with the NewsHour on PBS . "
            "In the nineteen eighties , barking dogs have increasingly become a problem in urban areas .",
            full_sliced_text)


class TestWorkflowHelper(unittest.TestCase):

    def setUp(self) -> None:
        self.maxDiff = None
        self.basic_mmif = Mmif(
            '{"metadata": {"mmif": "http://mmif.clams.ai/1.0.0"}, "documents": [{"@type": "http://mmif.clams.ai/vocabulary/VideoDocument/v1", "properties": {"id": "d1", "mime": "video/mp4", "location": "file:///test/video.mp4"}}], "views": []}'
        )

    def create_temp_mmif_file(self, mmif_obj):
        """Helper to create a temporary MMIF file."""
        tmp = tempfile.NamedTemporaryFile(mode='w', suffix='.mmif', delete=False)
        if isinstance(mmif_obj, Mmif):
            content_to_write = mmif_obj.serialize(pretty=False)
        else:
            content_to_write = json.dumps(mmif_obj)
        tmp.write(content_to_write)
        tmp.close()
        return tmp.name

    def test_split_appname_appversion(self):
        app_name, app_version = wfh._split_appname_appversion("http://apps.clams.ai/test-app/v1.0.0")
        self.assertEqual(app_name, "test-app")
        self.assertEqual(app_version, "v1.0.0")

    def test_generate_param_hash(self):
        params = {"param1": "value1", "param2": 42}
        hash1 = wfh.generate_param_hash(params)
        hash2 = wfh.generate_param_hash(params)
        self.assertEqual(hash1, hash2)
        params_reversed = {"param2": 42, "param1": "value1"}
        hash3 = wfh.generate_param_hash(params_reversed)
        self.assertEqual(hash1, hash3)

    def test_generate_workflow_identifier_grouped(self):
        view1 = self.basic_mmif.new_view()
        view1.metadata.app = "http://apps.clams.ai/app1/v1.0.0"
        view1.metadata.timestamp = "2024-01-01T12:00:00Z"
        view2 = self.basic_mmif.new_view()
        view2.metadata.app = "http://apps.clams.ai/app1/v1.0.0"
        view2.metadata.timestamp = "2024-01-01T12:00:00Z"
        view3 = self.basic_mmif.new_view()
        view3.metadata.app = "http://apps.clams.ai/app2/v2.0.0"
        view3.metadata.timestamp = "2024-01-01T12:01:00Z"
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        import os
        try:
            workflow_id = wfh.generate_workflow_identifier(tmp_file)
            segments = workflow_id.split('/')
            self.assertEqual(len(segments), 7)
            self.assertIn('app1', segments[1])
            self.assertIn('app2', segments[4])
        finally:
            os.unlink(tmp_file)

    def test_generate_workflow_identifier_with_mmif_object(self):
        """Test that generate_workflow_identifier accepts Mmif objects directly."""
        import os

        # Test with Mmif object directly
        workflow_id_from_obj = wfh.generate_workflow_identifier(self.basic_mmif)

        # Test with file path - should produce the same result
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            workflow_id_from_file = wfh.generate_workflow_identifier(tmp_file)
            self.assertEqual(workflow_id_from_obj, workflow_id_from_file)
        finally:
            os.unlink(tmp_file)

    def test_read_mmif_from_path(self):
        """Test the _read_mmif_from_path helper function."""

        # Test with Mmif object - should return as-is
        result = wfh._read_mmif_from_path(self.basic_mmif)
        self.assertIs(result, self.basic_mmif)

        # Test with file path string
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result_from_str = wfh._read_mmif_from_path(tmp_file)
            self.assertIsInstance(result_from_str, Mmif)
            self.assertEqual(result_from_str.serialize(pretty=False), self.basic_mmif.serialize(pretty=False))

            # Test with Path object
            result_from_path = wfh._read_mmif_from_path(Path(tmp_file))
            self.assertIsInstance(result_from_path, Mmif)
            self.assertEqual(result_from_path.serialize(pretty=False), self.basic_mmif.serialize(pretty=False))
        finally:
            os.unlink(tmp_file)

        # Test with invalid input
        with pytest.raises(ValueError):
            wfh._read_mmif_from_path(12345)

    def test_describe_single_mmif_with_mmif_object(self):
        """Test that describe_single_mmif accepts Mmif objects directly."""
        import os

        # Test with Mmif object directly
        result_from_obj = wfh.describe_single_mmif(self.basic_mmif)

        # Test with file path - should produce the same result
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result_from_file = wfh.describe_single_mmif(tmp_file)
            self.assertEqual(result_from_obj, result_from_file)
            
            # Validate that the output conforms to the SingleMmifDesc Pydantic model
            # If validation succeeds, all required fields with correct aliases are present
            validated = wfh.SingleMmifDesc.model_validate(result_from_obj)
            # Can assert on the validated object's attributes if needed
            self.assertIsNotNone(validated.workflow_id)
            self.assertIsNotNone(validated.stats)
            self.assertIsNotNone(validated.apps)
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_empty(self):
        """Test describe_single_mmif with an empty MMIF (no views)."""
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 0)
            self.assertEqual(len(validated.apps), 0)
            self.assertEqual(validated.stats.annotation_count_by_type, {})
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_one_app(self):
        """Test describe_single_mmif with a single app execution."""
        view = self.basic_mmif.new_view()
        view.metadata.app = "http://apps.clams.ai/test-app/v1.0.0"
        view.metadata.timestamp = "2024-01-01T12:00:00Z"
        view.metadata.appProfiling = {"runningTime": "0:00:01.234"}
        view.new_annotation(AnnotationTypes.TimeFrame)
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 1)
            self.assertEqual(len(validated.apps), 1)
            app_exec = validated.apps[0]
            self.assertEqual(app_exec.app, view.metadata.app)
            self.assertEqual(app_exec.view_ids, [view.id])
            self.assertEqual(app_exec.app_profiling.running_time_ms, 1234)
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_one_app_two_views(self):
        """Test describe_single_mmif with one app execution producing two views."""
        view1 = self.basic_mmif.new_view()
        view1.metadata.app = "http://apps.clams.ai/test-app/v1.0.0"
        view1.metadata.timestamp = "2024-01-01T12:00:00Z"
        view1.new_annotation(AnnotationTypes.TimeFrame)
        view2 = self.basic_mmif.new_view()
        view2.metadata.app = "http://apps.clams.ai/test-app/v1.0.0"
        view2.metadata.timestamp = "2024-01-01T12:00:00Z"
        view2.new_annotation(AnnotationTypes.TimeFrame)
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 1)
            self.assertEqual(len(validated.apps), 1)
            app_exec = validated.apps[0]
            self.assertEqual(app_exec.view_ids, [view1.id, view2.id])
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_error_view(self):
        """Test describe_single_mmif with a view containing an error."""
        view = self.basic_mmif.new_view()
        view.metadata.app = "http://apps.clams.ai/test-app/v1.0.0"
        view.metadata.timestamp = "2024-01-01T12:00:00Z"
        view.metadata.error = {"message": "Something went wrong"}
        tmp_file = self.create_temp_mmif_file(self.basic_mmif)
        try:
            result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 0)
            self.assertEqual(len(validated.apps), 0)
            self.assertEqual(len(validated.stats.error_views), 1)
        finally:
            os.unlink(tmp_file)

    def test_describe_single_mmif_with_unassigned_views(self):
        """Test describe_single_mmif with views that cannot be grouped."""
        import unittest.mock
        raw_mmif = json.loads(self.basic_mmif.serialize())
        raw_mmif['views'].append({'id': 'v1', 'metadata': {'app': 'http://apps.clams.ai/app1/v1.0.0', 'timestamp': '2024-01-01T12:00:00Z'}, 'annotations': []})
        raw_mmif['views'].append({'id': 'v2', 'metadata': {'app': 'http://apps.clams.ai/app2/v2.0.0'}, 'annotations': []})
        raw_mmif['views'].append({'id': 'v3', 'metadata': {'timestamp': '2024-01-01T12:01:00Z', 'app': ''}, 'annotations': []})
        tmp_file = self.create_temp_mmif_file(raw_mmif)
        try:
            with unittest.mock.patch('jsonschema.validators.validate'):
                result = wfh.describe_single_mmif(tmp_file)
            # Validate against Pydantic model
            validated = wfh.SingleMmifDesc.model_validate(result)
            self.assertEqual(validated.stats.app_count, 1)
            self.assertEqual(len(validated.apps), 2)
            special_entry = validated.apps[-1]
            self.assertEqual(special_entry.app, 'http://apps.clams.ai/non-existing-app/v1')
            self.assertEqual(len(special_entry.view_ids), 2)
            self.assertIn('v2', special_entry.view_ids)
            self.assertIn('v3', special_entry.view_ids)
        finally:
            os.unlink(tmp_file)

    def test_describe_collection_empty(self):
        """Test describe_mmif_collection with an empty directory."""
        dummy_dir = 'dummy_mmif_collection'
        os.makedirs(dummy_dir, exist_ok=True)
        try:
            output = wfh.describe_mmif_collection(dummy_dir)
            # Validate using Pydantic model
            validated = wfh.CollectionMmifDesc.model_validate(output)
            self.assertEqual(validated.mmif_count_by_status.total, 0)
            self.assertEqual(len(validated.workflows), 0)
        finally:
            os.rmdir(dummy_dir)

    def test_describe_collection_with_files(self):
        """Test describe_mmif_collection with MMIF files."""
        dummy_dir = 'dummy_mmif_collection_with_files'
        os.makedirs(dummy_dir, exist_ok=True)
        try:
            # Create two MMIF files in the directory
            for i in range(2):
                tmp_file = os.path.join(dummy_dir, f'{i}.mmif')
                with open(tmp_file, 'w') as f:
                    f.write(self.basic_mmif.serialize())
            
            output = wfh.describe_mmif_collection(dummy_dir)
            
            # Validate structure using Pydantic model
            # If validation succeeds, all required fields with correct aliases are present
            validated = wfh.CollectionMmifDesc.model_validate(output)
            
            # Verify counts using validated object attributes
            self.assertEqual(validated.mmif_count_by_status.total, 2)
            self.assertIsInstance(validated.workflows, list)
        finally:
            import shutil
            shutil.rmtree(dummy_dir)


if __name__ == '__main__':
    unittest.main()
